### ISSUE TITLE
MalformedJsonException on getPkgs

### ISSUE THREAD

**Issue by emilianbold** [foojay2020/discoclient#1]
The server response doesn't always have the expected format and we get MalformedJsonException:

```
com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2 path $.info
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894)
        at com.google.gson.Gson.fromJson(Gson.java:927)
Caused: com.google.gson.JsonSyntaxException
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at io.foojay.api.discoclient.DiscoClient.getPkgs(DiscoClient.java:307)
```

**Comment by HanSolo** [comment]
Could you provide an example call to reproduce the issue?

**Comment by emilianbold** [comment]
That's all I got.

I suspect it's some error condition on the server side that gets converted into something that's not quite a JSON and has an "info" field?

**Comment by geertjanw** [comment]
What was the API call you use, @emilianbold?

**Comment by emilianbold** [comment]
It was io.foojay.api.discoclient.DiscoClient.getPkgs(DiscoClient.java:307) which called whatever on the server side.
