### ISSUE TITLE
NPE due to expired ephemeralId

### ISSUE THREAD

**Issue by emilianbold** [foojay2020/discoclient#8]
For the NetBeans plugin I'm seeing

```
java.lang.NullPointerException
	at io.foojay.api.discoclient.DiscoClient.getPkgInfo(DiscoClient.java:1160)
	at org.netbeans.modules.java.disco.Client.getPkgInfo(Client.java:87)
	at org.netbeans.modules.java.disco.DownloadPanel.lambda$downloadBundle$0(DownloadPanel.java:113)
```

An expired ephemeralId returns a JSON like:

```json
{
  "value":"c0a94587dd7058aa1a50006dd7aacc206d97d0aa",
  "detail":"Requested ephemeral id cannot be found or is outdated.",
  "supported":"Valid ephemeral id from package."
}
```

then discoclient tries to exact the filename and fails:

```java
            final String     filename          = packageInfoJson.get(PkgInfo.FIELD_FILENAME).getAsString();
```

**Comment by emilianbold** [comment]
PR #10 fixes this.
